### ISSUE TITLE
error building sample

### ISSUE THREAD

**Issue by Rovel** [firebase/friendlypix-web#1]
Hi,
I just cloned and applied the readme steps in a new project but when I run `npm run serve` some errors appears in the browser console and the app hides the login buttons as the image shows:
![screen shot 2017-07-21 at 21 54 30](https://user-images.githubusercontent.com/2469500/28487047-dea20f54-6e5f-11e7-9f47-41d90eaeb04c.png)

**Comment by Sitarman** [comment]
Same here on Ubuntu 16

**Comment by victorv** [comment]
PR https://github.com/firebase/friendlypix-web/pull/3 fixes the problem on OS X 10.11.6

**Comment by darwindlrd** [comment]
Same here on Windows 10

**Comment by Rovel** [comment]
thanks @victorv any preview on the merge? are you from the core team?

**Comment by dhirajbajaj** [comment]
same here..

**Comment by nicolasgarnier** [comment]
We'll merge this soon. We re-organized our repos and I lost access to this one (although I'm the main maintainer). As soon as I'm getting access back I'll merge all this :)

**Comment by nicolasgarnier** [comment]
should be fixed now!

**Comment by Rovel** [comment]
Thanks!!!

**Comment by isidorodasilva** [comment]
<img width="1280" alt="screen shot 2018-01-18 at 8 44 14 pm" src="https://user-images.githubusercontent.com/16050469/35115304-634156a2-fc90-11e7-9747-f19cf44e04a6.png">
 

please advise the issue is still happening is something wrong my end ?or the server side, kindly support.

**Comment by nicolasgarnier** [comment]
Usually that means the .js files don't exists. Se we are serving the HTML page (since this is a single-page web app).

Most likely you forgot to run `npm run build`  which installs the dependencies and generates (transpile) the JS files.

**Comment by isidorodasilva** [comment]
<img width="1274" alt="screen shot 2018-01-18 at 9 45 47 pm" src="https://user-images.githubusercontent.com/16050469/35117985-0bf7a460-fc99-11e7-9028-73ed2af21d79.png">

i ran the "npm run build" command now i get the error that @Rovel was having. . . 
kindly assist @nicolasgarnier ...

**Comment by nicolasgarnier** [comment]
@isidorodasilva,

Can you tell me which platform you are on? (Windows, Mac, Linux)

Also can you make sure you have the following files at the root:

.babelrc
.bowerrc
.eslintrc

Can you also copy paste the output of your `npm run build` command?

**Comment by isidorodasilva** [comment]
Hi Nicolas,
im running on a Mac, 

im have searched for the files and cant be found ,
out put of npm run build is

> npm WARN firebase-functions@0.6.3 requires a peer of firebase-admin@~5.2.1 but none is installed. You must install peer dependencies yourself.

**Comment by nicolasgarnier** [comment]
OK it looks like you are missing these files and it's likely  causing the issue. can you download them from the repo:

![image](https://user-images.githubusercontent.com/3766663/35123381-38543434-fca2-11e7-82e4-e0d407f8eed2.png)

**Comment by isidorodasilva** [comment]
thanks ... issue closed , the files are considered system files and were hidden.. thank you very much @nicolasgarnier

**Comment by nicolasgarnier** [comment]
Glad it worked for you!
